from sqlalchemy import JSON, Column, ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID

from app.db.base import Base


class VendorSchema(Base):
    __tablename__ = "vendor_schemas"

    # SHA-256 prefix of sorted top-level payload key names — identifies a vendor's schema shape
    schema_fingerprint = Column(String(16), nullable=False, unique=True, index=True)
    entity_type = Column(String(20), nullable=False)
    # JSON extraction spec generated by the LLM on first encounter
    extraction_spec = Column(JSON, nullable=False)
    # Raw event that triggered spec generation, for auditability
    sample_raw_payload_id = Column(UUID(as_uuid=True), ForeignKey("raw_events.id", ondelete="SET NULL"), nullable=True)
