"""Add vendor_schemas table for reusable extraction specs.

Each row stores a JSON extraction spec generated by the LLM on first encounter
with a new vendor schema shape. Subsequent payloads with the same schema fingerprint
are processed deterministically without an LLM call.

Revision ID: 20260527_03
Revises: 20240527_01
Create Date: 2026-05-27 23:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260527_03"
down_revision: str | None = "20240527_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "vendor_schemas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("schema_fingerprint", sa.String(length=16), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("extraction_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sample_raw_payload_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["sample_raw_payload_id"], ["raw_events.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vendor_schemas_id"), "vendor_schemas", ["id"], unique=False)
    op.create_unique_constraint("uq_vendor_schemas_fingerprint", "vendor_schemas", ["schema_fingerprint"])


def downgrade() -> None:
    op.drop_constraint("uq_vendor_schemas_fingerprint", "vendor_schemas", type_="unique")
    op.drop_index(op.f("ix_vendor_schemas_id"), table_name="vendor_schemas")
    op.drop_table("vendor_schemas")
